### ISSUE TITLE
Better onboarding

### ISSUE THREAD

**Issue by ditmarvisser** [ENDER-9/Vocascan#141]
Having just installed the app, there are a few issues I have with the learning process. I made a package with a group with 18 words to learn, and these are all questions I have about the whole process.

1. Vocabs per day
What does this value mean? Nowhere in the app or in the documentation is this explained. Does "vocabs per day" mean how many you WANT to learn in a day? How many you CAN learn in a day? I dont know. Maybe if you have a library of more than that value of words it's limited to that value?

2. "Correct translations to have succesful vocabulary pairs"
Again, what does this mean? Explained nowhere that I can find. I've set it to multiple values but it doesnt seem to do anything during creation of the groups or the learning process.

3. Activating a group
I made a group with 18 words to learn. On the "Learn" page I need to click activate. What does this mean? During the creation of the package and group I made sure the active switch is turned on.

4. Repeated learning
When I start the group on the learn page I have to go through the entire list. After that, I can click learn. I go through the entire list again. But then I cant learn that group anymore. Activate and Learn are both greyed out. I think repetition is the best way to learn a language, so only being able to learn a group of words once doesnt seem that good.

Now it could be that all this information is available somewhere, but I havent been able to find it. I think it would be good to have this information available in the app, at least in in the documentation. The docs are now focused on istalling the app, and they are very thorough and good to follow, but using the app could use some more documentation.

**Comment by noctera** [comment]
Hi, thanks for reaching out. Unfortunately we haven't documented the functions of the vocabulary trainer yet,as we dont have that much functions yet. Only the install process, as you have already noticed. But I like to answer your questions:

4. I will start with this question, as the other questions can be answered more easily, when explained this. 
Vocascan is currently based on an learning algorithm, that will create daily queries. With this you have multiple stages a vocab card can be put in. Based on the result, if you know this vocab card queried in you daily query, it gets put in a lower or higher stage. Those stages have different intervals/repetition times.

Here is a wiki article for a better understanding:

https://en.m.wikipedia.org/wiki/Spaced_repetition

This is why "Learn" is grayed out, after you learned the vocabs. Successful learned vocabs will be put in the next stage, that gets queried in two days. Wrong vocabs get queried the next day.

1. "vocab per day" means how many vocabs you WANT to learn per day. When you have 300 vocabs in your inbox, and set this variable to 100, you will only get 100 a day, the next part (again 100) the next day and so on...


2. Unfortunately this function is nowhere implemented, except the input field for this variable. This was a function, that was planned earlier, but wasn't implemented due to design changes. We will delete it in the next update.

3. In the vocab trainer you have two options when creating vocabs. "Active" and "Activate". 

Active just decides whether the vocab or group gets put in your daily query or not. With this you can easily deactive a group of vocabs if you don't want them to be put in your queries.

Activate is a function where you can add vocabs, which are put in the daily query directly. You first have to "activate" them, by going through them once. This is ideal if you have a book of vocabs with different chapters, add everything of it in the vocab trainer, but don't want to learn everything yet. When the time has come, you can just select the group you want to activate and add it to your daily query. (Currently you are thrown into a query with all unactivated vocabs. This will change in the next update, where you can choose specific groups)

The difference between the Active and Activate property is, that Activate is like an introduction to this specific group you want to add to your knowledge, by going through it once before adding it.

Ps: in the next update there is a basic "custom learning" function planed, where you can start queries with specific groups independently of your current status of you daily query. Something like a custom query that doesn't count to you stats and are just for personal repetition.

I hope I could help out with this. If you still have any questions, please let me know :)

**Comment by ditmarvisser** [comment]
Thanks for the swift reply! This answers all my questions perfectly. It's good to know the philosophy behind the trainer. I think it has a solid base that, with a few more features, can act as a great tool to learn new vocabs. 

I'll keep up to date with the development. My language course has a break in a few weeks, so if it's welcomed I'll try to contribute some things to the codebase.

Thanks for developing the tool!
